import os
from pathlib import Path

os.environ.setdefault("DATABASE_URL", "sqlite:///:memory:")
os.environ.setdefault("INTERNAL_SERVICE_KEY", "test-key")
os.environ.setdefault("EMBEDDING_PROVIDER", "google")
os.environ.setdefault("GOOGLE_EMBEDDING_MODEL", "models/gemini-embedding-2-preview")
os.environ.setdefault("EMBEDDING_DIMENSION", "3072")

from app.pdf_pipeline.chunker import chunk_paper, normalize_section_name


FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "papers"


def _sample_content() -> str:
    return (FIXTURE_DIR / "llamaparse_sample_ieee.md").read_text(encoding="utf-8")


def test_abstract_is_dedicated_chunk():
    chunks = chunk_paper(
        title="Structure-Aware RAG",
        abstract="This paper improves retrieval over scientific PDFs.",
        content=_sample_content(),
    )

    abstract_chunks = [c for c in chunks if c.chunk_type == "abstract"]
    assert len(abstract_chunks) == 1
    assert abstract_chunks[0].section == "abstract"
    assert "Title: Structure-Aware RAG" in abstract_chunks[0].content_for_embedding


def test_chunks_do_not_include_references():
    chunks = chunk_paper(
        title="Structure-Aware RAG",
        abstract="Short abstract.",
        content=_sample_content(),
    )

    combined = "\n".join(c.content for c in chunks)
    assert "This reference should not be included" not in combined


def test_section_normalization():
    assert normalize_section_name("Proposed Approach") == "methodology"
    assert normalize_section_name("Evaluation") == "results"
    assert normalize_section_name("Related Work") == "related_work"
    assert normalize_section_name("Future Work") == "conclusion"


def test_long_table_caption_does_not_become_an_oversized_section():
    caption = (
        "Table 1: Examples of potential users, tasks, and questions generated by the LLM "
        "based on short descriptions of the target datasets. Questions target global "
        "understanding rather than specific details."
    )

    assert normalize_section_name(caption) == "other"


def test_custom_section_slug_is_bounded_to_database_limit():
    normalized = normalize_section_name("A " + "very long custom heading " * 20)

    assert len(normalized) <= 128


def test_chunk_metadata_is_complete():
    chunks = chunk_paper(
        title="Structure-Aware RAG",
        abstract="Short abstract.",
        content=_sample_content(),
    )

    assert chunks
    for index, chunk in enumerate(chunks):
        assert chunk.chunk_index == index
        assert chunk.chunk_type
        assert chunk.section
        assert chunk.heading_path
        assert chunk.token_count >= 0
        assert chunk.chunking_version == "v2"


def test_markdown_table_small_is_preserved_as_table_chunk():
    chunks = chunk_paper(
        title="Structure-Aware RAG",
        abstract="Short abstract.",
        content=_sample_content(),
    )

    table_chunks = [c for c in chunks if c.chunk_type == "table"]
    assert table_chunks
    assert "TABLE I." in table_chunks[0].content
    assert "| Method | Precision@5 | Recall@8 |" in table_chunks[0].content
    assert "Structure-aware chunking" in table_chunks[0].content


def test_large_table_is_split_and_repeats_header(monkeypatch):
    monkeypatch.setattr("app.pdf_pipeline.chunker.settings.TABLE_MAX_ROWS_PER_CHUNK", 2)
    rows = "\n".join(f"| Method {i} | 0.{i} | 0.{i + 1} |" for i in range(6))
    content = f"""## Evaluation

TABLE II. Large benchmark table

| Method | Precision@5 | Recall@8 |
|---|---:|---:|
{rows}
"""

    chunks = chunk_paper("Large Table Paper", "Short abstract.", content)
    table_chunks = [c for c in chunks if c.chunk_type == "table"]

    assert len(table_chunks) == 3
    assert all("| Method | Precision@5 | Recall@8 |" in c.content for c in table_chunks)
    assert all("TABLE II. Large benchmark table" in c.content for c in table_chunks)


def test_caption_and_algorithm_blocks_are_detected():
    chunks = chunk_paper(
        title="Structure-Aware RAG",
        abstract="Short abstract.",
        content=_sample_content(),
    )

    assert any(c.chunk_type == "figure_caption" and "Fig. 1." in c.content for c in chunks)
    assert any(c.chunk_type == "formula_or_algorithm" and "Algorithm 1" in c.content for c in chunks)
