"""
RAG Workflow — main entry point for the Deep Research pipeline.

Routing logic:
1. If session_id is provided and a Research_Context exists in Redis,
   route to FastChatAgent (single LLM call, <30 s).
2. Otherwise run the full 6-agent pipeline with timing instrumentation.

After the full pipeline completes, the Research_Context is saved to Redis
so that subsequent follow-up questions can use Fast Chat Mode.

Requirements: 1.7, 3.1, 3.2, 8.1, 8.2, 8.3, 8.4
"""

from __future__ import annotations

import logging
import time
from typing import Callable, Optional

from app.agents.clarifier import ClarifierAgent
from app.agents.fast_chat import FastChatAgent
from app.agents.planner import PlannerAgent
from app.agents.reader import ReaderAgent
from app.agents.researcher import ResearcherAgent
from app.agents.reviewer import ReviewerAgent
from app.agents.writer import WriterAgent
from app.core.config import settings
from app.core.llm import get_safe_llm
from app.core.memory_store import MemoryStore, SessionContextNotFoundError
from app.core.redis_client import create_redis_client
from app.schemas.chat_models import Message, MessageRole, ResearchReport, Source
from app.workflows.states import AgentState

logger = logging.getLogger(__name__)


def _elapsed_ms(start: float) -> int:
    return int((time.perf_counter() - start) * 1000)


def _describe_model(llm) -> dict:
    """Return safe, user-facing model metadata without exposing credentials."""
    usage_snapshot = getattr(llm, "usage_snapshot", None)
    if callable(usage_snapshot):
        return usage_snapshot()

    candidates = getattr(llm, "candidates", None)
    if isinstance(candidates, list) and candidates:
        return {
            "provider": "OpenRouter",
            "model": None,
            "status": "configured",
            "routing": f"OpenRouter candidates · {len(candidates)} available",
            "available_models": [str(candidate) for candidate in candidates],
            "attempts": [],
        }

    model = getattr(llm, "model_name", None) or getattr(llm, "model", None)
    if not isinstance(model, str) or not model.strip():
        model = getattr(settings, "GROQ_LLM_MODEL", "Configured model")
    return {
        "provider": str(getattr(settings, "AGENT_LLM_PROVIDER", "Configured")).title(),
        "model": str(model),
        "routing": "Direct provider",
        "status": "configured",
        "fallback_used": False,
        "attempts": [],
    }


def _emit_progress(
    callback: Optional[Callable[[dict], None]],
    *,
    phase: str,
    state: str,
    agent: str = "system",
    title: str,
    detail: str = "",
    message: Optional[str] = None,
    iteration: int = 0,
    max_iterations: int = 2,
    metadata: Optional[dict] = None,
    source_previews: Optional[list[dict]] = None,
) -> None:
    """Emit bounded, user-facing workflow events without affecting the pipeline."""
    if callback is None:
        return
    try:
        callback(
            {
                "phase": phase,
                "state": state,
                "agent": agent,
                "title": title,
                "detail": detail,
                "message": message or title,
                "iteration": iteration,
                "max_iterations": max_iterations,
                "metadata": metadata or {},
                "source_previews": source_previews or [],
            }
        )
    except Exception:
        logger.warning("Deep research progress callback failed", exc_info=True)


# ---------------------------------------------------------------------------
# Helper: persist fast-chat messages to conversation history
# ---------------------------------------------------------------------------


def _persist_fast_chat(
    store: MemoryStore,
    session_id: str,
    question: str,
    answer: str,
) -> None:
    """Save the user question and assistant answer to the session's message history.

    Args:
        store:      Initialised MemoryStore instance.
        session_id: UUID of the session.
        question:   The follow-up question from the user.
        answer:     The fast-chat answer generated by FastChatAgent.
    """
    try:
        user_msg = Message(
            session_id=session_id,
            role=MessageRole.USER,
            content=question,
        )
        store.save_message(session_id, user_msg)

        assistant_msg = Message(
            session_id=session_id,
            role=MessageRole.ASSISTANT,
            content=answer,
        )
        store.save_message(session_id, assistant_msg)

        logger.debug(
            "_persist_fast_chat: saved 2 messages for session %s", session_id
        )
    except Exception as exc:  # pragma: no cover
        logger.warning(
            "_persist_fast_chat: failed to persist messages for session %s: %s",
            session_id,
            exc,
        )


# ---------------------------------------------------------------------------
# Helper: save Research_Context after full pipeline
# ---------------------------------------------------------------------------


def _save_research_context(session_id: str, result: dict) -> None:
    """Persist the pipeline result as a Research_Context in Redis.

    Called after the full pipeline completes so that subsequent follow-up
    questions can be handled by FastChatAgent (Fast Chat Mode).

    Args:
        session_id: UUID of the session.
        result:     Final state dict returned by the compiled graph.

    Requirements: 1.7
    """
    redis_client = None
    try:
        redis_client = create_redis_client()
        store = MemoryStore(redis_client)

        # Build ResearchReport from pipeline result
        # A rejected draft is still useful conversation context, but it must not
        # be promoted to reviewed_answer. Preserve it with its review metadata.
        report_answer: str = (
            result.get("reviewed_answer") or result.get("draft_answer") or ""
        )
        confidence_score: float = float(result.get("confidence_score", 0.0))
        review_feedback: str = result.get("review_feedback") or ""

        # Convert external_context dicts → Source objects
        raw_sources: list = result.get("external_context", [])
        sources: list[Source] = []
        for idx, src in enumerate(raw_sources, start=1):
            if isinstance(src, dict):
                sources.append(
                    Source(
                        index=idx,
                        type=src.get("type") or src.get("source_type", "url"),
                        title=src.get("title", ""),
                        url=src.get("url", ""),
                        arxiv_id=src.get("arxiv_id"),
                        authors=src.get("authors", []),
                        year=src.get("year"),
                        venue=src.get("venue"),
                        abstract=src.get("abstract"),
                        citation_count=src.get("citation_count"),
                    )
                )

        research_report = ResearchReport(
            answer=report_answer,
            sources=sources,
            confidence_score=confidence_score,
            review_feedback=review_feedback,
        )

        store.init_session_context(
            session_id=session_id,
            research_report=research_report,
            sources=sources,
        )

        logger.info(
            "_save_research_context: saved context for session %s (%d sources)",
            session_id,
            len(sources),
        )
    except Exception as exc:  # pragma: no cover
        logger.warning(
            "_save_research_context: failed for session %s: %s",
            session_id,
            exc,
        )
    finally:
        if redis_client is not None:
            try:
                redis_client.close()
            except Exception:
                pass


# ---------------------------------------------------------------------------
# Main workflow entry point
# ---------------------------------------------------------------------------


def run_chat_workflow(
    question: str,
    article_id: Optional[int] = None,
    session_id: Optional[str] = None,
    progress_callback: Optional[Callable[[dict], None]] = None,
) -> dict:
    """Route to FastChatAgent or full pipeline based on session Research_Context.

    Routing logic:
    - If *session_id* is provided and the session has a ``research_report``
      stored in Redis, use FastChatAgent (single LLM call).
    - If *session_id* is provided but no context exists
      (``SessionContextNotFoundError``), fall through to the full pipeline.
    - If *session_id* is None, run the full pipeline directly.

    Timing instrumentation (Requirement 8.1–8.4):
    - ``start_time`` is recorded at function entry.
    - Each agent call is wrapped with ``time.time()`` to populate
      ``planner_time``, ``researcher_time``, ``writer_time``, ``reviewer_time``
      in the returned state dict.
    - Total elapsed is logged on completion.
    - A WARNING is emitted when total elapsed exceeds 300 s.

    Args:
        question:   The user's research question or follow-up query.
        article_id: Optional article ID for paper-specific (non-deep-research) mode.
        session_id: Optional session UUID for context routing.
        progress_callback: Optional observer for structured pipeline progress.

    Returns:
        Final state dict (keys match ``AgentState`` fields plus any agent-added keys).

    Requirements: 1.7, 3.1, 3.2, 8.1, 8.2, 8.3, 8.4
    """
    # ── Task 7.3: record start time ──────────────────────────────────────────
    start_time = time.time()
    start_perf = time.perf_counter()
    timings: dict[str, int] = {
        "context_lookup_ms": 0,
        "planner_ms": 0,
        "clarifier_ms": 0,
        "researcher_ms": 0,
        "reader_ms": 0,
        "keyword_search_ms": 0,
        "embedding_ms": 0,
        "vector_search_ms": 0,
        "merge_rank_ms": 0,
        "load_parents_ms": 0,
        "intent_ms": 0,
        "tenant_lookup_ms": 0,
        "total_retrieval_ms": 0,
        "retrieval_ms": 0,
        "writer_ms": 0,
        "reviewer_ms": 0,
        "external_search_collect_ms": 0,
        "external_search_retry_ms": 0,
        "researcher_llm_ms": 0,
        "context_save_ms": 0,
        "fast_answer_ms": 0,
        "total_latency_ms": 0,
    }

    # ── Task 7.1: Research_Context routing ───────────────────────────────────
    if session_id:
        redis_client = create_redis_client()
        try:
            context = None
            store = MemoryStore(redis_client)
            try:
                t0 = time.perf_counter()
                context = store.get_context_window(session_id)
                timings["context_lookup_ms"] = _elapsed_ms(t0)
            except SessionContextNotFoundError:
                # No context in Redis -> fall through to full pipeline.
                pass
            except Exception as exc:  # pragma: no cover
                logger.warning(
                    "run_chat_workflow: context lookup failed for session %s: %s — "
                    "falling through to full pipeline",
                    session_id,
                    exc,
                )

            if context is not None and context.research_report is not None:
                # ── Fast Chat Mode ────────────────────────────────────────────
                logger.info(
                    "run_chat_workflow: session=%s mode=fast_chat", session_id
                )

                agent = FastChatAgent(get_safe_llm("fast_chat"))
                t0 = time.perf_counter()
                result = agent.run(question, context)
                timings["fast_answer_ms"] = _elapsed_ms(t0)

                # Persist question + answer to conversation history
                _persist_fast_chat(store, session_id, question, result["answer"])

                elapsed = time.time() - start_time
                timings["total_latency_ms"] = _elapsed_ms(start_perf)
                result["timings"] = timings
                logger.info(
                    "run_chat_workflow: fast_chat completed in %.2fs for session=%s",
                    elapsed,
                    session_id,
                )
                return result

            # context exists but no research_report → fall through to full pipeline
        finally:
            try:
                redis_client.close()
            except Exception:
                pass

    # ── Full pipeline (Tasks 7.2 + 7.3) ─────────────────────────────────────
    logger.info(
        "run_chat_workflow: session=%s mode=full_pipeline", session_id
    )

    state = AgentState(question=question, article_id=article_id)

    # Instantiate agents (same models as build_graph.py)
    planner_llm = get_safe_llm("planner")
    clarifier_llm = get_safe_llm("clarifier")
    researcher_llm = get_safe_llm("researcher")
    reviewer_llm = get_safe_llm("reviewer")
    planner    = PlannerAgent(planner_llm)
    clarifier  = ClarifierAgent(clarifier_llm)
    researcher = ResearcherAgent(researcher_llm)
    reader     = ReaderAgent()
    writer_llm = get_safe_llm("writer")
    writer     = WriterAgent(writer_llm)
    writer_model_config = _describe_model(writer_llm)
    reviewer   = ReviewerAgent(reviewer_llm)
    model_usage: dict[str, dict] = {
        "reader": {
            "agent": "reader",
            "provider": "Internal retrieval",
            "model": None,
            "status": "not_applicable",
            "routing": "PGVector context",
            "fallback_used": False,
            "attempts": [],
        },
    }

    # ── Planner ──────────────────────────────────────────────────────────────
    _emit_progress(
        progress_callback,
        phase="planning",
        state="active",
        agent="planner",
        title="Planning research",
        detail="PlannerAgent is analyzing the question and defining the research scope.",
    )
    t0 = time.time()
    p0 = time.perf_counter()
    state = planner.run(state)
    model_usage["planner"] = _describe_model(planner_llm)
    state.planner_time = time.time() - t0
    state.timings["planner_ms"] = _elapsed_ms(p0)
    logger.debug("planner_time=%.2fs", state.planner_time)
    _emit_progress(
        progress_callback,
        phase="planning",
        state="completed",
        agent="planner",
        title="Research plan complete",
        detail=(
            f"Created {len(state.search_queries)} queries and identified "
            f"{len(state.focus_sections)} focus areas."
        ),
        metadata={
            "search_queries": state.search_queries[:5],
            "focus_sections": state.focus_sections[:10],
            "need_external_search": state.need_external_search,
            "model": model_usage["planner"].get("model"),
            "provider": model_usage["planner"].get("provider"),
            "duration_ms": state.timings["planner_ms"],
        },
    )

    # ── Clarifier ────────────────────────────────────────────────────────────
    if state.need_clarification:
        _emit_progress(
            progress_callback,
            phase="clarifying",
            state="active",
            agent="clarifier",
            title="Clarifying the research question",
            detail="ClarifierAgent is standardizing the interpretation before source discovery.",
        )
    p0 = time.perf_counter()
    state = clarifier.run(state)
    model_usage["clarifier"] = _describe_model(clarifier_llm)
    state.timings["clarifier_ms"] = _elapsed_ms(p0)
    if state.need_clarification:
        _emit_progress(
            progress_callback,
            phase="clarifying",
            state="completed",
            agent="clarifier",
            title="Research question clarified",
            detail="The question has been normalized for consistent use across the pipeline.",
            metadata={"duration_ms": state.timings["clarifier_ms"]},
        )
    else:
        _emit_progress(
            progress_callback,
            phase="clarifying",
            state="skipped",
            agent="clarifier",
            title="Question is already clear",
            detail="No additional clarification was needed.",
            metadata={"duration_ms": state.timings["clarifier_ms"]},
        )

    # ── Researcher ───────────────────────────────────────────────────────────
    if state.need_external_search:
        _emit_progress(
            progress_callback,
            phase="searching",
            state="active",
            agent="researcher",
            title="Searching academic sources",
            detail=f"ResearcherAgent is processing up to {min(len(state.search_queries), 5)} queries.",
            metadata={"total_queries": min(len(state.search_queries), 5)},
        )
    else:
        _emit_progress(
            progress_callback,
            phase="searching",
            state="skipped",
            agent="researcher",
            title="No external search needed",
            detail="PlannerAgent determined that no additional web search is required.",
        )
    t0 = time.time()
    p0 = time.perf_counter()
    state = researcher.run(state, progress_callback=progress_callback)
    model_usage["researcher"] = _describe_model(researcher_llm)
    state.researcher_time = time.time() - t0
    state.timings["researcher_ms"] = _elapsed_ms(p0)
    logger.debug("researcher_time=%.2fs", state.researcher_time)

    # ── Reader ───────────────────────────────────────────────────────────────
    _emit_progress(
        progress_callback,
        phase="synthesizing",
        state="skipped" if article_id is None else "active",
        agent="reader",
        title=(
            "ReaderAgent skipped"
            if article_id is None
            else "ReaderAgent is reading internal documents"
        ),
        detail=(
            "This session has no linked internal document; continuing with external sources."
            if article_id is None
            else "ReaderAgent is retrieving relevant passages from the personal library."
        ),
    )
    p0 = time.perf_counter()
    state = reader.run(state)
    model_usage["reader"]["duration_ms"] = _elapsed_ms(p0)
    state.timings["reader_ms"] = _elapsed_ms(p0)
    if article_id is not None:
        _emit_progress(
            progress_callback,
            phase="synthesizing",
            state="completed",
            agent="reader",
            title="ReaderAgent finished retrieval",
            detail="Relevant internal passages are ready for synthesis.",
            metadata={"duration_ms": state.timings["reader_ms"]},
        )

    # ── Writer → Reviewer loop (mirrors _review_router in build_graph.py) ────
    while True:
        draft_iteration = state.iteration_count + 1
        _emit_progress(
            progress_callback,
            phase="drafting",
            state="active",
            agent="writer",
            title=f"Writing draft {draft_iteration}",
            detail=(
                "WriterAgent is synthesizing evidence and building a cited report."
                + (f" Focus: {', '.join(state.focus_sections[:4])}." if state.focus_sections else "")
            ),
            iteration=draft_iteration,
            max_iterations=state.max_iterations,
            metadata={
                "model_status": "selecting",
                "available_models": writer_model_config.get("available_models", []),
            },
        )
        t0 = time.time()
        p0 = time.perf_counter()
        state = writer.run(state)
        model_usage["writer"] = _describe_model(writer_llm)
        writer_model = model_usage["writer"]
        state.writer_time = time.time() - t0
        state.timings["writer_ms"] = state.timings.get("writer_ms", 0) + _elapsed_ms(p0)
        logger.debug("writer_time=%.2fs", state.writer_time)
        _emit_progress(
            progress_callback,
            phase="drafting",
            state="completed",
            agent="writer",
            title=f"Draft {draft_iteration} complete",
            detail="The draft is ready for quality review.",
            iteration=draft_iteration,
            max_iterations=state.max_iterations,
            metadata={
                "draft_length": len(state.draft_answer or ""),
                "model": writer_model.get("model"),
                "provider": writer_model.get("provider"),
                "model_status": writer_model.get("status"),
                "fallback_used": writer_model.get("fallback_used", False),
                "model_attempts": writer_model.get("attempts", []),
                "duration_ms": state.timings.get("writer_ms", 0),
            },
        )

        _emit_progress(
            progress_callback,
            phase="reviewing",
            state="active",
            agent="reviewer",
            title=f"Reviewing draft {draft_iteration}",
            detail="ReviewerAgent is checking completeness, citations, and source quality.",
            iteration=draft_iteration,
            max_iterations=state.max_iterations,
        )
        t0 = time.time()
        p0 = time.perf_counter()
        state = reviewer.run(state)
        model_usage["reviewer"] = _describe_model(reviewer_llm)
        state.reviewer_time = time.time() - t0
        state.timings["reviewer_ms"] = state.timings.get("reviewer_ms", 0) + _elapsed_ms(p0)
        logger.debug("reviewer_time=%.2fs", state.reviewer_time)

        should_rewrite = (
            state.reviewed_answer is None
            and state.confidence_score < 0.7
            and state.iteration_count < state.max_iterations
        )
        review_decision = (
            "accept" if state.reviewed_answer is not None
            else "rewrite" if should_rewrite
            else "rejected"
        )
        _emit_progress(
            progress_callback,
            phase="reviewing",
            state="completed",
            agent="reviewer",
            title=f"Draft {state.iteration_count} reviewed",
            detail=state.review_feedback or "ReviewerAgent did not provide additional feedback.",
            iteration=state.iteration_count,
            max_iterations=state.max_iterations,
            metadata={
                "score": state.confidence_score,
                "decision": review_decision,
                "iteration": state.iteration_count,
                "focus_sections": state.focus_sections[:6],
                "model": model_usage["reviewer"].get("model"),
                "provider": model_usage["reviewer"].get("provider"),
                "model_status": model_usage["reviewer"].get("status"),
                "model_attempts": model_usage["reviewer"].get("attempts", []),
                "duration_ms": state.timings.get("reviewer_ms", 0),
            },
        )

        # Replicate _review_router logic from build_graph.py
        if should_rewrite:
            # Trigger rewrite loop
            _emit_progress(
                progress_callback,
                phase="rewriting",
                state="active",
                agent="writer",
                title=f"Preparing draft rewrite {state.iteration_count + 1}",
                detail=state.review_feedback or "The draft needs improvement based on the quality review.",
                iteration=state.iteration_count + 1,
                max_iterations=state.max_iterations,
            )
            continue
        break

    _emit_progress(
        progress_callback,
        phase="finalizing",
        state="active",
        agent="system",
        title="Finalizing the report",
        detail="DeepScholar is packaging the final content, sources, and metadata.",
        iteration=state.iteration_count,
        max_iterations=state.max_iterations,
    )
    result = state.model_dump()
    result["writer_model"] = model_usage.get("writer", writer_model_config)
    result["model_usage"] = model_usage

    # ── Task 7.2: save Research_Context after pipeline ───────────────────────
    if session_id and (result.get("reviewed_answer") or result.get("draft_answer")):
        p0 = time.perf_counter()
        _save_research_context(session_id, result)
        state.timings["context_save_ms"] = _elapsed_ms(p0)

    # ── Task 7.3: log total elapsed + slow-query warning ─────────────────────
    elapsed = time.time() - start_time
    state.timings["total_latency_ms"] = _elapsed_ms(start_perf)
    result["timings"] = {**timings, **state.timings}
    logger.info(
        "run_chat_workflow: full_pipeline completed in %.2fs "
        "(planner=%.2fs researcher=%.2fs writer=%.2fs reviewer=%.2fs) session=%s",
        elapsed,
        state.planner_time,
        state.researcher_time,
        state.writer_time,
        state.reviewer_time,
        session_id,
    )

    if elapsed > 300:  # Requirement 8.4
        logger.warning(
            "run_chat_workflow: SLOW QUERY — exceeded 300s (%.2fs) for "
            "query='%s' session=%s "
            "(planner=%.2fs researcher=%.2fs writer=%.2fs reviewer=%.2fs)",
            elapsed,
            question[:100],
            session_id,
            state.planner_time,
            state.researcher_time,
            state.writer_time,
            state.reviewer_time,
        )

    _emit_progress(
        progress_callback,
        phase="completed",
        state="completed",
        agent="system",
        title="Research report complete",
        detail=(
            f"Report completed with "
            f"{len([s for s in state.external_context if s.get('title') != '__research_notes__'])} sources."
        ),
        message="Research report completed",
        iteration=state.iteration_count,
        max_iterations=state.max_iterations,
        metadata={
            "confidence_score": state.confidence_score,
            "iterations_used": state.iteration_count,
            "total_latency_ms": state.timings.get("total_latency_ms", 0),
        },
    )
    return result
