"""
RAG Workflow — main entry point for the Deep Research pipeline.

Routing logic:
1. If session_id is provided and a Research_Context exists in Redis,
   route to FastChatAgent (single LLM call, <30 s).
2. Otherwise run the full 6-agent pipeline with timing instrumentation.

After the full pipeline completes, the Research_Context is saved to Redis
so that subsequent follow-up questions can use Fast Chat Mode.

Requirements: 1.7, 3.1, 3.2, 8.1, 8.2, 8.3, 8.4
"""

from __future__ import annotations

import logging
import time
import uuid
from typing import Callable, Optional

from app.agents.fast_chat import FastChatAgent
from app.core.graph_checkpoint import get_graph_checkpointer
from app.graph.build_graph import build_graph
from app.core.llm import get_safe_llm
from app.core.memory_store import MemoryStore, SessionContextNotFoundError
from app.core.redis_client import create_redis_client
from app.schemas.chat_models import Message, MessageRole, ResearchReport, Source
from app.workflows.states import AgentState

logger = logging.getLogger(__name__)


def _elapsed_ms(start: float) -> int:
    return int((time.perf_counter() - start) * 1000)


def _emit_progress(
    callback: Optional[Callable[[dict], None]],
    *,
    phase: str,
    state: str,
    agent: str = "system",
    title: str,
    detail: str = "",
    message: Optional[str] = None,
    iteration: int = 0,
    max_iterations: int = 2,
    metadata: Optional[dict] = None,
    source_previews: Optional[list[dict]] = None,
) -> None:
    """Emit bounded, user-facing workflow events without affecting the pipeline."""
    if callback is None:
        return
    try:
        callback(
            {
                "phase": phase,
                "state": state,
                "agent": agent,
                "title": title,
                "detail": detail,
                "message": message or title,
                "iteration": iteration,
                "max_iterations": max_iterations,
                "metadata": metadata or {},
                "source_previews": source_previews or [],
            }
        )
    except Exception:
        logger.warning("Deep research progress callback failed", exc_info=True)


# ---------------------------------------------------------------------------
# Helper: persist fast-chat messages to conversation history
# ---------------------------------------------------------------------------


def _persist_fast_chat(
    store: MemoryStore,
    session_id: str,
    question: str,
    answer: str,
) -> None:
    """Save the user question and assistant answer to the session's message history.

    Args:
        store:      Initialised MemoryStore instance.
        session_id: UUID of the session.
        question:   The follow-up question from the user.
        answer:     The fast-chat answer generated by FastChatAgent.
    """
    try:
        user_msg = Message(
            session_id=session_id,
            role=MessageRole.USER,
            content=question,
        )
        store.save_message(session_id, user_msg)

        assistant_msg = Message(
            session_id=session_id,
            role=MessageRole.ASSISTANT,
            content=answer,
        )
        store.save_message(session_id, assistant_msg)

        logger.debug(
            "_persist_fast_chat: saved 2 messages for session %s", session_id
        )
    except Exception as exc:  # pragma: no cover
        logger.warning(
            "_persist_fast_chat: failed to persist messages for session %s: %s",
            session_id,
            exc,
        )


# ---------------------------------------------------------------------------
# Helper: save Research_Context after full pipeline
# ---------------------------------------------------------------------------


def _save_research_context(session_id: str, result: dict) -> None:
    """Persist the pipeline result as a Research_Context in Redis.

    Called after the full pipeline completes so that subsequent follow-up
    questions can be handled by FastChatAgent (Fast Chat Mode).

    Args:
        session_id: UUID of the session.
        result:     Final state dict returned by the compiled graph.

    Requirements: 1.7
    """
    redis_client = None
    try:
        redis_client = create_redis_client()
        store = MemoryStore(redis_client)

        # Build ResearchReport from pipeline result
        report_answer: str = result.get("reviewed_answer") or ""
        if not report_answer:
            logger.info("_save_research_context: not saving rejected report for session %s", session_id)
            return
        confidence_score: float = float(result.get("confidence_score", 0.0))
        review_feedback: str = result.get("review_feedback") or ""

        # Convert external_context dicts → Source objects
        raw_sources: list = result.get("external_context", [])
        sources: list[Source] = []
        for idx, src in enumerate(raw_sources, start=1):
            if isinstance(src, dict):
                sources.append(
                    Source(
                        index=idx,
                        type=src.get("type") or src.get("source_type", "url"),
                        title=src.get("title", ""),
                        url=src.get("url", ""),
                        arxiv_id=src.get("arxiv_id"),
                        authors=src.get("authors", []),
                        year=src.get("year"),
                        venue=src.get("venue"),
                        abstract=src.get("abstract"),
                        citation_count=src.get("citation_count"),
                    )
                )

        research_report = ResearchReport(
            answer=report_answer,
            sources=sources,
            confidence_score=confidence_score,
            review_feedback=review_feedback,
        )

        store.init_session_context(
            session_id=session_id,
            research_report=research_report,
            sources=sources,
        )

        logger.info(
            "_save_research_context: saved context for session %s (%d sources)",
            session_id,
            len(sources),
        )
    except Exception as exc:  # pragma: no cover
        logger.warning(
            "_save_research_context: failed for session %s: %s",
            session_id,
            exc,
        )
    finally:
        if redis_client is not None:
            try:
                redis_client.close()
            except Exception:
                pass


# ---------------------------------------------------------------------------
# Main workflow entry point
# ---------------------------------------------------------------------------


def run_chat_workflow(
    question: str,
    article_id: Optional[int] = None,
    session_id: Optional[str] = None,
    progress_callback: Optional[Callable[[dict], None]] = None,
) -> dict:
    """Route to FastChatAgent or full pipeline based on session Research_Context.

    Routing logic:
    - If *session_id* is provided and the session has a ``research_report``
      stored in Redis, use FastChatAgent (single LLM call).
    - If *session_id* is provided but no context exists
      (``SessionContextNotFoundError``), fall through to the full pipeline.
    - If *session_id* is None, run the full pipeline directly.

    Timing instrumentation is initialized here and may be enriched by agents.

    Args:
        question:   The user's research question or follow-up query.
        article_id: Optional article ID for paper-specific (non-deep-research) mode.
        session_id: Optional session UUID for context routing.
        progress_callback: Optional observer for structured pipeline progress.

    Returns:
        Final state dict (keys match ``AgentState`` fields plus any agent-added keys).

    Requirements: 1.7, 3.1, 3.2, 8.1, 8.2, 8.3, 8.4
    """
    # ── Task 7.3: record start time ──────────────────────────────────────────
    start_time = time.time()
    start_perf = time.perf_counter()
    timings: dict[str, int] = {
        "context_lookup_ms": 0,
        "planner_ms": 0,
        "clarifier_ms": 0,
        "researcher_ms": 0,
        "reader_ms": 0,
        "keyword_search_ms": 0,
        "embedding_ms": 0,
        "vector_search_ms": 0,
        "merge_rank_ms": 0,
        "load_parents_ms": 0,
        "intent_ms": 0,
        "tenant_lookup_ms": 0,
        "total_retrieval_ms": 0,
        "retrieval_ms": 0,
        "writer_ms": 0,
        "reviewer_ms": 0,
        "external_search_collect_ms": 0,
        "external_search_retry_ms": 0,
        "researcher_llm_ms": 0,
        "context_save_ms": 0,
        "fast_answer_ms": 0,
        "total_latency_ms": 0,
    }

    # ── Task 7.1: Research_Context routing ───────────────────────────────────
    if session_id:
        redis_client = create_redis_client()
        try:
            context = None
            store = MemoryStore(redis_client)
            try:
                t0 = time.perf_counter()
                context = store.get_context_window(session_id)
                timings["context_lookup_ms"] = _elapsed_ms(t0)
            except SessionContextNotFoundError:
                # No context in Redis -> fall through to full pipeline.
                pass
            except Exception as exc:  # pragma: no cover
                logger.warning(
                    "run_chat_workflow: context lookup failed for session %s: %s — "
                    "falling through to full pipeline",
                    session_id,
                    exc,
                )

            if context is not None and context.research_report is not None:
                # ── Fast Chat Mode ────────────────────────────────────────────
                logger.info(
                    "run_chat_workflow: session=%s mode=fast_chat", session_id
                )

                agent = FastChatAgent(get_safe_llm("fast_chat"))
                t0 = time.perf_counter()
                result = agent.run(question, context)
                timings["fast_answer_ms"] = _elapsed_ms(t0)

                # Persist question + answer to conversation history
                _persist_fast_chat(store, session_id, question, result["answer"])

                elapsed = time.time() - start_time
                timings["total_latency_ms"] = _elapsed_ms(start_perf)
                result["timings"] = timings
                logger.info(
                    "run_chat_workflow: fast_chat completed in %.2fs for session=%s",
                    elapsed,
                    session_id,
                )
                return result

            # context exists but no research_report → fall through to full pipeline
        finally:
            try:
                redis_client.close()
            except Exception:
                pass

    # ── Full pipeline (Tasks 7.2 + 7.3) ─────────────────────────────────────
    logger.info(
        "run_chat_workflow: session=%s mode=full_pipeline", session_id
    )

    # LangGraph is the single orchestration source for full Deep Research.
    # Fast Chat routing above remains intentionally outside this graph.
    graph_state = AgentState(
        question=question,
        article_id=article_id,
        checkpoint_thread_id=session_id,
        timings=timings,
    )
    graph = build_graph(
        checkpointer=get_graph_checkpointer(),
        progress_callback=progress_callback,
    )
    graph_config = {"configurable": {"thread_id": session_id or f"research-{uuid.uuid4()}"}}
    result = graph.invoke(graph_state, config=graph_config)
    result["timings"] = timings
    if session_id and result.get("reviewed_answer"):
        _save_research_context(session_id, result)
    return result
