"""
RAG Workflow — main entry point for the Deep Research pipeline.

Routing logic:
1. If session_id is provided and a Research_Context exists in Redis,
   route to FastChatAgent (single LLM call, <30 s).
2. Otherwise run the full 6-agent pipeline with timing instrumentation.

After the full pipeline completes, the Research_Context is saved to Redis
so that subsequent follow-up questions can use Fast Chat Mode.

Requirements: 1.7, 3.1, 3.2, 8.1, 8.2, 8.3, 8.4
"""

from __future__ import annotations

import logging
import time
from typing import Optional

import redis as redis_lib

from app.agents.clarifier import ClarifierAgent
from app.agents.fast_chat import FastChatAgent
from app.agents.planner import PlannerAgent
from app.agents.reader import ReaderAgent
from app.agents.researcher import ResearcherAgent
from app.agents.reviewer import ReviewerAgent
from app.agents.writer import WriterAgent
from app.core.config import settings
from app.core.llm import get_safe_llm
from app.core.memory_store import MemoryStore, SessionContextNotFoundError
from app.schemas.chat_models import Message, MessageRole, ResearchReport, Source
from app.workflows.states import AgentState

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helper: persist fast-chat messages to conversation history
# ---------------------------------------------------------------------------


def _persist_fast_chat(
    store: MemoryStore,
    session_id: str,
    question: str,
    answer: str,
) -> None:
    """Save the user question and assistant answer to the session's message history.

    Args:
        store:      Initialised MemoryStore instance.
        session_id: UUID of the session.
        question:   The follow-up question from the user.
        answer:     The fast-chat answer generated by FastChatAgent.
    """
    try:
        user_msg = Message(
            session_id=session_id,
            role=MessageRole.USER,
            content=question,
        )
        store.save_message(session_id, user_msg)

        assistant_msg = Message(
            session_id=session_id,
            role=MessageRole.ASSISTANT,
            content=answer,
        )
        store.save_message(session_id, assistant_msg)

        logger.debug(
            "_persist_fast_chat: saved 2 messages for session %s", session_id
        )
    except Exception as exc:  # pragma: no cover
        logger.warning(
            "_persist_fast_chat: failed to persist messages for session %s: %s",
            session_id,
            exc,
        )


# ---------------------------------------------------------------------------
# Helper: save Research_Context after full pipeline
# ---------------------------------------------------------------------------


def _save_research_context(session_id: str, result: dict) -> None:
    """Persist the pipeline result as a Research_Context in Redis.

    Called after the full pipeline completes so that subsequent follow-up
    questions can be handled by FastChatAgent (Fast Chat Mode).

    Args:
        session_id: UUID of the session.
        result:     Final state dict returned by the compiled graph.

    Requirements: 1.7
    """
    redis_client = None
    try:
        redis_client = redis_lib.from_url(settings.REDIS_URL)
        store = MemoryStore(redis_client)

        # Build ResearchReport from pipeline result
        reviewed_answer: str = result.get("reviewed_answer") or ""
        confidence_score: float = float(result.get("confidence_score", 0.0))
        review_feedback: str = result.get("review_feedback") or ""

        # Convert external_context dicts → Source objects
        raw_sources: list = result.get("external_context", [])
        sources: list[Source] = []
        for idx, src in enumerate(raw_sources, start=1):
            if isinstance(src, dict):
                sources.append(
                    Source(
                        index=idx,
                        type=src.get("type") or src.get("source_type", "url"),
                        title=src.get("title", ""),
                        url=src.get("url", ""),
                        arxiv_id=src.get("arxiv_id"),
                        authors=src.get("authors", []),
                        year=src.get("year"),
                        venue=src.get("venue"),
                        abstract=src.get("abstract"),
                        citation_count=src.get("citation_count"),
                    )
                )

        research_report = ResearchReport(
            answer=reviewed_answer,
            sources=sources,
            confidence_score=confidence_score,
            review_feedback=review_feedback,
        )

        store.init_session_context(
            session_id=session_id,
            research_report=research_report,
            sources=sources,
        )

        logger.info(
            "_save_research_context: saved context for session %s (%d sources)",
            session_id,
            len(sources),
        )
    except Exception as exc:  # pragma: no cover
        logger.warning(
            "_save_research_context: failed for session %s: %s",
            session_id,
            exc,
        )
    finally:
        if redis_client is not None:
            try:
                redis_client.close()
            except Exception:
                pass


# ---------------------------------------------------------------------------
# Main workflow entry point
# ---------------------------------------------------------------------------


def run_chat_workflow(
    question: str,
    article_id: Optional[int] = None,
    session_id: Optional[str] = None,
) -> dict:
    """Route to FastChatAgent or full pipeline based on session Research_Context.

    Routing logic:
    - If *session_id* is provided and the session has a ``research_report``
      stored in Redis, use FastChatAgent (single LLM call).
    - If *session_id* is provided but no context exists
      (``SessionContextNotFoundError``), fall through to the full pipeline.
    - If *session_id* is None, run the full pipeline directly.

    Timing instrumentation (Requirement 8.1–8.4):
    - ``start_time`` is recorded at function entry.
    - Each agent call is wrapped with ``time.time()`` to populate
      ``planner_time``, ``researcher_time``, ``writer_time``, ``reviewer_time``
      in the returned state dict.
    - Total elapsed is logged on completion.
    - A WARNING is emitted when total elapsed exceeds 300 s.

    Args:
        question:   The user's research question or follow-up query.
        article_id: Optional article ID for paper-specific (non-deep-research) mode.
        session_id: Optional session UUID for context routing.

    Returns:
        Final state dict (keys match ``AgentState`` fields plus any agent-added keys).

    Requirements: 1.7, 3.1, 3.2, 8.1, 8.2, 8.3, 8.4
    """
    # ── Task 7.3: record start time ──────────────────────────────────────────
    start_time = time.time()

    # ── Task 7.1: Research_Context routing ───────────────────────────────────
    if session_id:
        redis_client = redis_lib.from_url(settings.REDIS_URL)
        try:
            store = MemoryStore(redis_client)
            context = store.get_context_window(session_id)

            if context.research_report is not None:
                # ── Fast Chat Mode ────────────────────────────────────────────
                logger.info(
                    "run_chat_workflow: session=%s mode=fast_chat", session_id
                )

                agent = FastChatAgent(get_safe_llm("fast_chat"))
                result = agent.run(question, context)

                # Persist question + answer to conversation history
                _persist_fast_chat(store, session_id, question, result["answer"])

                elapsed = time.time() - start_time
                logger.info(
                    "run_chat_workflow: fast_chat completed in %.2fs for session=%s",
                    elapsed,
                    session_id,
                )
                return result

            # context exists but no research_report → fall through to full pipeline

        except SessionContextNotFoundError:
            # No context in Redis → fall through to full pipeline
            pass
        except Exception as exc:  # pragma: no cover
            logger.warning(
                "run_chat_workflow: error checking Research_Context for session %s: %s — "
                "falling through to full pipeline",
                session_id,
                exc,
            )
        finally:
            try:
                redis_client.close()
            except Exception:
                pass

    # ── Full pipeline (Tasks 7.2 + 7.3) ─────────────────────────────────────
    logger.info(
        "run_chat_workflow: session=%s mode=full_pipeline", session_id
    )

    state = AgentState(question=question, article_id=article_id)

    # Instantiate agents (same models as build_graph.py)
    planner    = PlannerAgent(get_safe_llm("planner"))
    clarifier  = ClarifierAgent(get_safe_llm("clarifier"))
    researcher = ResearcherAgent(get_safe_llm("researcher"))
    reader     = ReaderAgent()
    writer     = WriterAgent(get_safe_llm("writer"))
    reviewer   = ReviewerAgent(get_safe_llm("reviewer"))

    # ── Planner ──────────────────────────────────────────────────────────────
    t0 = time.time()
    state = planner.run(state)
    state.planner_time = time.time() - t0
    logger.debug("planner_time=%.2fs", state.planner_time)

    # ── Clarifier ────────────────────────────────────────────────────────────
    state = clarifier.run(state)

    # ── Researcher ───────────────────────────────────────────────────────────
    t0 = time.time()
    state = researcher.run(state)
    state.researcher_time = time.time() - t0
    logger.debug("researcher_time=%.2fs", state.researcher_time)

    # ── Reader ───────────────────────────────────────────────────────────────
    state = reader.run(state)

    # ── Writer → Reviewer loop (mirrors _review_router in build_graph.py) ────
    while True:
        t0 = time.time()
        state = writer.run(state)
        state.writer_time = time.time() - t0
        logger.debug("writer_time=%.2fs", state.writer_time)

        t0 = time.time()
        state = reviewer.run(state)
        state.reviewer_time = time.time() - t0
        logger.debug("reviewer_time=%.2fs", state.reviewer_time)

        # Replicate _review_router logic from build_graph.py
        if (
            state.reviewed_answer is None
            and state.confidence_score < 0.7
            and state.iteration_count < state.max_iterations
        ):
            # Trigger rewrite loop
            continue
        break

    result = state.model_dump()

    # ── Task 7.2: save Research_Context after pipeline ───────────────────────
    if session_id and result.get("reviewed_answer"):
        _save_research_context(session_id, result)

    # ── Task 7.3: log total elapsed + slow-query warning ─────────────────────
    elapsed = time.time() - start_time
    logger.info(
        "run_chat_workflow: full_pipeline completed in %.2fs "
        "(planner=%.2fs researcher=%.2fs writer=%.2fs reviewer=%.2fs) session=%s",
        elapsed,
        state.planner_time,
        state.researcher_time,
        state.writer_time,
        state.reviewer_time,
        session_id,
    )

    if elapsed > 300:  # Requirement 8.4
        logger.warning(
            "run_chat_workflow: SLOW QUERY — exceeded 300s (%.2fs) for "
            "query='%s' session=%s "
            "(planner=%.2fs researcher=%.2fs writer=%.2fs reviewer=%.2fs)",
            elapsed,
            question[:100],
            session_id,
            state.planner_time,
            state.researcher_time,
            state.writer_time,
            state.reviewer_time,
        )

    return result
